[package]
name = "mosers_powers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rug]
version = "1.19.2"
default-features = false
features = ["integer"]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio", "html_reports"] }

[[bench]]
name = "qrt_100"
harness = false

[profile.bench]
debug = true

[profile.release]
debug = true